services:
  redis:
    image: redis:7-alpine
    container_name: observo-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - observo_network
    command: redis-server --requirepass observo --appendonly yes --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD:-observo }', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  redis_data:
