/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appDashboardRouteRouteImport } from './routes/(app)/dashboard/route'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as appDashboardIndexRouteImport } from './routes/(app)/dashboard/index'
import { Route as appDashboardApiKeysRouteImport } from './routes/(app)/dashboard/api-keys'
import { Route as appDashboardLiveRouteImport } from './routes/(app)/dashboard/live'
import { Route as appDashboardLogsRouteImport } from './routes/(app)/dashboard/logs'
import { Route as appDashboardSdkRouteImport } from './routes/(app)/dashboard/sdk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRouteRoute = appDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardApiKeysRoute = appDashboardApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardLiveRoute = appDashboardLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardLogsRoute = appDashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardSdkRoute = appDashboardSdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => appDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard/api-keys': typeof appDashboardApiKeysRoute
  '/dashboard/live': typeof appDashboardLiveRoute
  '/dashboard/logs': typeof appDashboardLogsRoute
  '/dashboard/sdk': typeof appDashboardSdkRoute
  '/dashboard/': typeof appDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard/api-keys': typeof appDashboardApiKeysRoute
  '/dashboard/live': typeof appDashboardLiveRoute
  '/dashboard/logs': typeof appDashboardLogsRoute
  '/dashboard/sdk': typeof appDashboardSdkRoute
  '/dashboard': typeof appDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(app)/dashboard': typeof appDashboardRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(app)/dashboard/api-keys': typeof appDashboardApiKeysRoute
  '/(app)/dashboard/live': typeof appDashboardLiveRoute
  '/(app)/dashboard/logs': typeof appDashboardLogsRoute
  '/(app)/dashboard/sdk': typeof appDashboardSdkRoute
  '/(app)/dashboard/': typeof appDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/api-keys'
    | '/dashboard/live'
    | '/dashboard/logs'
    | '/dashboard/sdk'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/api-keys'
    | '/dashboard/live'
    | '/dashboard/logs'
    | '/dashboard/sdk'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)'
    | '/(app)/dashboard'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(app)/dashboard/api-keys'
    | '/(app)/dashboard/live'
    | '/(app)/dashboard/logs'
    | '/(app)/dashboard/sdk'
    | '/(app)/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/api-keys': {
      id: '/(app)/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof appDashboardApiKeysRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/live': {
      id: '/(app)/dashboard/live'
      path: '/live'
      fullPath: '/dashboard/live'
      preLoaderRoute: typeof appDashboardLiveRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/logs': {
      id: '/(app)/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof appDashboardLogsRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/sdk': {
      id: '/(app)/dashboard/sdk'
      path: '/sdk'
      fullPath: '/dashboard/sdk'
      preLoaderRoute: typeof appDashboardSdkRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
  }
}

interface appDashboardRouteRouteChildren {
  appDashboardApiKeysRoute: typeof appDashboardApiKeysRoute
  appDashboardLiveRoute: typeof appDashboardLiveRoute
  appDashboardLogsRoute: typeof appDashboardLogsRoute
  appDashboardSdkRoute: typeof appDashboardSdkRoute
  appDashboardIndexRoute: typeof appDashboardIndexRoute
}

const appDashboardRouteRouteChildren: appDashboardRouteRouteChildren = {
  appDashboardApiKeysRoute: appDashboardApiKeysRoute,
  appDashboardLiveRoute: appDashboardLiveRoute,
  appDashboardLogsRoute: appDashboardLogsRoute,
  appDashboardSdkRoute: appDashboardSdkRoute,
  appDashboardIndexRoute: appDashboardIndexRoute,
}

const appDashboardRouteRouteWithChildren =
  appDashboardRouteRoute._addFileChildren(appDashboardRouteRouteChildren)

interface appRouteRouteChildren {
  appDashboardRouteRoute: typeof appDashboardRouteRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDashboardRouteRoute: appDashboardRouteRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
